### ISSUE TITLE
add yaehmop include dir in conda build

### ISSUE THREAD

**Issue by richardjgowers** [greglandrum/yaehmop#27]
For the next release we'll have to check that the conda build is correctly shipping the new headers.

**Comment by richardjgowers** [comment]
@greglandrum if you've got time to push a release tag I can put this in the conda-forge build

**Comment by greglandrum** [comment]
@richardjgowers I can tag a release pretty much whenever.
Are you ok with me sticking with the date-based numbering scheme? So this one could be v2019.03.1

**Comment by richardjgowers** [comment]
Yep that works for me

**Comment by greglandrum** [comment]
https://github.com/greglandrum/yaehmop/releases/tag/v2019.03.1

**Comment by richardjgowers** [comment]
ok done, conda-forge builds now ship with headers & lib (& blas)
