### ISSUE TITLE
Overlap integrals implemented

### ISSUE THREAD

**Issue by Leticia-maria** [greglandrum/yaehmop#36]
Which overlap integrals are implemented on this package? @greglandrum

**Comment by greglandrum** [comment]
Extended Hueckel theory just requires overlap integrals using slater-type orbitals (not Gaussians). These are implemented in this file: https://github.com/greglandrum/yaehmop/blob/cfb5aeebbdf5ae93c4f4eeb14c7a507dea54ae9e/tightbind/mov.c

**Comment by Leticia-maria** [comment]
Thanks, but do you have the paper that shows the formalism of your implementation? @greglandrum I would like to cite, because I am implementing something relatable

**Comment by Leticia-maria** [comment]
Could you share? Thanks for your attention @greglandrum 🤗

**Comment by greglandrum** [comment]
@Leticia-maria I don't have a reference for that. The implementation in YAeHMOP was ported from a much older fortran implementation.

**Comment by ghutchis** [comment]
I would guess the most appropriate references would be Roald's EHT papers. I haven't checked the "Orbital Interactions" textbook if it mentions much about the implementation.

e.g.
https://doi.org/10.1063/1.1734456
https://doi.org/10.1063/1.1725601
